export const initialCommerceSettings = [
	{ key: "site.name", value: "老实人AI" },
	{ key: "site.description", value: "" },
	{ key: "site.seo_title", value: "" },
	{ key: "site.seo_description", value: "" },
	{ key: "site.custom_html", value: "" },
	{ key: "site.default_locale", value: "en-US" },
	{ key: "site.logo_url", value: "" },
	{ key: "orders.allow_guest_checkout", value: true },
	{ key: "orders.default_expiry_ms", value: 900_000 },
	{ key: "orders.max_quantity", value: 100 },
	{ key: "automation.artifact_retention_ms", value: 2_592_000_000 },
	{ key: "queue.publish_batch_size", value: 25 },
	{ key: "queue.retry_base_ms", value: 15_000 },
	{ key: "auth.registration_enabled", value: true },
	{ key: "auth.require_email_verification", value: false },
	{ key: "auth.session_max_age_seconds", value: 2_592_000 },
	{ key: "retention.audit_ms", value: 31_536_000_000 },
	{ key: "commerce.default_currency", value: "USD" },
	{ key: "commerce.currency_decimals", value: 2 },
	{ key: "commerce.currency_symbol", value: "$" },
] as const;
